### ISSUE TITLE
Too Many Requests (RFC 6585) (HTTP 429)

### ISSUE THREAD

**Issue by EthiopiaB** [ropensci-archive/dbhydroR#22]
Looping through multiple stations to download data for each station (dbkey). It keeps brining up this error "Error in dbh_GET(servfull, query = qy) Too Many Requests (RFC 6585) (HTTP 429)". It appears that the server is overwhelmed by the request and stops writing the data to either a dataframe or csv.

**Comment by jsta** [comment]
You could try adding a call to `Sys.sleep(time)` before/after each loop iteration.

**Comment by EthiopiaB** [comment]
Thank you. I had done that. I set the delay to 30 seconds but still facing the same problem.
